Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "../../", "/vagrant"
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 2048
  end
end
